<?php
include 'model.php';
 $action= new Contacts;
 if($_GET['cmd']==="0"){
 	$action->addContact();
 }
 if($_GET['cmd']==="1"){
 	$action->recordContact();
 }
 if($_GET['cmd']==="2"){
 	$action->deleteContact();
 }
 if($_GET['cmd']==="3"){
 	$action->editRecord();
 }
 if($_GET['cmd']==="4"){
 	$action->editGroupList();
 }
 if($_GET['cmd']==="5"){
 	$action->addGroupList();
 }
 if($_GET['cmd']==="6"){
 	$action->delGroupList();
 }
 if($_GET['cmd']==="7"){
 	$action->addNumList();
 }
 if($_GET['cmd']==="8"){
 	$action->delNumList();
 }
 if($_GET['cmd']==="9"){
 	$action->updateNum();
 }
 if($_GET['cmd']==="10"){
 	$action->updateName();
 }
 if($_GET['cmd']==="11"){
 	$action->addGroup();
 }
 if($_GET['cmd']==="12"){
 	$action->delGroup();
 }
 if($_GET['cmd']==="13"){
 	$action->more();
 }
?>